# Generated by Django 3.0.5 on 2020-04-04 01:44

from django.db import migrations


class Migration(migrations.Migration):

    def create_data(apps, schema_editor):
        Customer = apps.get_model('customers', 'Customer')
        Customer(first_name="Customer 001", last_name="Customer 001", email="customer001@email.com", phone="00000000", address="Customer 000 Address", description= "Customer 001 description").save()


    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
